Book.create(title: "And Then There Were None", author: "Agatha Christie,Solidor", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523300890/01.jpg", description: "First, there were ten—a curious assortment of strangers summoned as weekend guests to a private island off the coast of Devon. Their host, an eccentric millionaire unknown to all of them, is nowhere to be found. All that the guests have in common is a wicked past they're unwilling to reveal—and a secret that will seal their fate. For each has been marked for murder. One by one they fall prey. Before the weekend is out, there will be none. And only the dead are above suspicion.")
Book.create(title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523386598/05.jpg", description: "A groundbreaking work of science fiction, The Left Hand of Darkness tells the story of a lone human emissary to Winter, an alien world whose inhabitants can choose -and change - their gender. His goal is to facilitate Winter's inclusion in a growing intergalactic civilization. But to do so he must bridge the gulf between his own views and those of the completely dissimilar culture that he encounters.

Embracing the aspects of psychology, society, and human emotion on an alien world, The Left Hand of Darkness stands as a landmark achievement in the annals of intellectual science fiction.")
Book.create(title: "The Casual Vacancy", author: "J.K. Rowling", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523386284/03.jpg", description: "When Barry Fairbrother dies in his early forties, the town of Pagford is left in shock.

Pagford is, seemingly, an English idyll, with a cobbled market square and an ancient abbey, but what lies behind the pretty façade is a town at war.

Rich at war with poor, teenagers at war with their parents, wives at war with their husbands, teachers at war with their pupils ... Pagford is not what it first seems.

And the empty seat left by Barry on the parish council soon becomes the catalyst for the biggest war the town has yet seen. Who will triumph in an election fraught with passion, duplicity and unexpected revelations?")
Book.create(title: "Crime and Punishment", author: "Fyodor Mikhaylovich Dostoyevsky", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523386227/02.jpg", description: "Raskolnikov, an impoverished student living in the St. Petersburg of the tsars, is determined to overreach his humanity and assert his untrammeled individual will. When he commits an act of murder and theft, he sets into motion a story that, for its excruciating suspense, its atmospheric vividness, and its depth of characterization and vision is almost unequaled in the literatures of the world. The best known of Dostoevsky’s masterpieces, Crime and Punishment can bear any amount of rereading without losing a drop of its power over our imaginations.

Dostoevsky’s drama of sin, guilt, and redemption transforms the sordid story of an old woman’s murder into the nineteenth century’s profoundest and most compelling philosophical novel.

Award-winning translators Richard Pevear and Larissa Volokhonsky render this elusive and wildly innovative novel with an energy, suppleness, and range of voice that do full justice to the genius of its creator.")
Book.create(title: "Notes from the Underground", author: "Fyodor Mikhaylovich Dostoyevsky", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523386434/04.jpg", description: "Dostoevsky’s most revolutionary novel, Notes from Underground marks the dividing line between nineteenth- and twentieth-century fiction, and between the visions of self each century embodied. One of the most remarkable characters in literature, the unnamed narrator is a former official who has defiantly withdrawn into an underground existence. In full retreat from society, he scrawls a passionate, obsessive, self-contradictory narrative that serves as a devastating attack on social utopianism and an assertion of man’s essentially irrational nature.

Richard Pevear and Larissa Volokhonsky, whose Dostoevsky translations have become the standard, give us a brilliantly faithful edition of this classic novel, conveying all the tragedy and tormented comedy of the original.")
Book.create(title: "The Big Four", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=MQRAVaVQGYIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Famed private eye Hercule Poirot tackles international intrigue and espionage in this classic Agatha Christie mystery.")
Book.create(title: "Verdict", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=P8Z4Mzxu9s8C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Melodrama Characters: 6 male, 4 female Interior Set The Hendryks, refugees in England, have lost everything.")
Book.create(title: "The Secret Adversary", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=4AeZP2ihPvsC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "In the midst of spinning an engrossing tale of adventure and international intrigue, Christie uses the novel to introduce the characters Tommy and Tuppence, both of whom figure in many of her books and short stories.")
Book.create(title: "The Four Suspects", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=S-VqWwZCSFQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Previously published in the print anthology The Thirteen Problems. A doctor who helped bring about the downfall of a secret German organization is convinced that the members will seek revenge")
Book.create(title: "The Clocks", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=1F4GAl314HQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Time is ticking away for a murderer in Agatha Christie’s classic, The Clocks, as Hercule Poirot investigates the strange case of a corpse surrounded by numerous timepieces in a blind woman’s house.")
Book.create(title: "The ABC Murders", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=79XFRzc4vdkC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "There&#39;s a serial killer on the loose, bent on working his way though the alphabet.")
Book.create(title: "After the Funeral", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=6Hw1_-iGGksC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Or are the siblings’ deaths just tragic coincidences? Desperate to know the truth, the Lansquenet’s solicitor turns to Hercule Poirot to unravel the mystery. For even after the funeral, death isn’t finished yet . . .")
Book.create(title: "The World's End", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=lMMYwMY_AzwC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Previously published in the print anthology The Mysterious Mr. Quin.")
Book.create(title: "Clues to Christie", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=_AGxDJ5PsEoC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Interspersed throughout are quotes from Christie, a list of the Christie novels that were her personal favorites and three of her classic short stories: The Affair at the Victory Ball, Greenshaw’s Folly and A Fairy in the Flat.")
Book.create(title: "The Thirteen Problems", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=IX2eax18FHEC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Miss Jane Marple is throwing a party, and the guests all have a story to tell--thirteen in all--each involving evil deeds and clever deduction.")
Book.create(title: "Witness for the Prosecution", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=ri-yyUadvWAC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Thriller / Characters: 8 male, 5 female Scenery: 2 Interiors Only Agatha Christie could have conceived such a suspenseful thriller and then capped it with an uncanny triple flip ending.")
Book.create(title: "The Red Signal", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=KbmJ8OtWTysC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Soon, a young man titled Dermot is drawn in and tells them both about the sixth sense he experiences, a red signal that spells danger. He is about to tell them of the last time he saw the red signal when he stops himself.")
Book.create(title: "Taken at the Flood", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=Ba7-doZhRqoC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Rosaleen Cloade has come to collect on her late husband&#39;s sizeable inheritance. But this is only the first intrusion on the Cloade family. The second is murder. And it is up to Detective Poirot to see the intrusions come to an end.")
Book.create(title: "Double Sin", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=l6qCPA-gdW0C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "These chilling stories, and more, cleverly wrought by master Agatha Christie and solved by the inimitable Hercule Poirot and Miss Jane Marple. Previously published in the print anthology Double Sin and Other Stories.")
Book.create(title: "A Fairy in the Flat", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=GVCKaqadCuoC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Previously published in the print anthology Partners in Crime.")
Book.create(title: "The Water Bus", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=1QY5AAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "A retelling of the Christmas Story in a way you’ve never heard it before. . . . The fable of a donkey who carries a mother and child safely to Egypt. . . . The tale of a widow who dislikes people until she meets a stranger. . .")
Book.create(title: "Murder on the Orient Express", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=cdC69SemSyIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "THE MOST WIDELY READ MYSTERY OF ALL TIME—NOW A MAJOR MOTION PICTURE DIRECTED BY KENNETH BRANAGH AND PRODUCED BY RIDLEY SCOTT! “The murderer is with us—on the train now . . .” Just after midnight, the famous Orient Express is stopped ...")
Book.create(title: "Agatha Christie: two classic mysteries in a single file", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=fjRRDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "According to the Guinness Book of World Records, Christie is the best-selling writer of books of all time and, with William Shakespeare, the best-selling author of any kind.")
Book.create(title: "The Actress", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=7b0eAAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Previously published in the print anthology The Harlequin Tea Set and Other Stories. Jake Levitt can’t believe his luck when, one evening at the theatre, he recognizes the lead actress as Nancy Taylor, a girl he knows a lot about.")
Book.create(title: "Problem at Sea: A Hercule Poirot Short Story", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=KZ-lAQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "A classic Agatha Christie short story, available individually for the first time as an ebook.")
Book.create(title: "The House of Lurking Death", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=eWw4to-OQhAC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Throwing on an almost convincing French accent, Tommy is determined to act the Great Detective Hanaud to his and Tuppence’s latest, lovely client.")
Book.create(title: "Cat Among the Pigeons", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=1o-ERABY8TsC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Murder is part of the curriculum at an exclusive school for girls in Agatha Christie’s Cat Among the Pigeons, as the intrepid Poirot sets out to bring a stealthy killer to justice.")
Book.create(title: "Sanctuary", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=bYCc75HccxQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Bunch, engrossed in her flower arrangements for the church, is placing the chrysanthemums when she sees a man crumpled over on the chancel steps, dying.")
Book.create(title: "The Dream", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=rIlwBzsr5Q8C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Farley wants him to diagnose his recurring dream of death, in which he shoots himself at precisely 3:28 p.m. Then, a week after dismissing Poirot, the dream becomes real.")
Book.create(title: "S.O.S.", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=lTPzWJjz7p8C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Previously published in the print anthology The Witness for the Prosecution and Other Stories.")
Book.create(title: "The Affair at the Victory Ball", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=AJLdCVQbRdoC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Previously published in the print anthology Poirot&#39;s Early Cases. A young lord is murdered at a masked ball, and his fiancée dies of a cocaine overdose. Can Poirot find out who the killer is?")
Book.create(title: "Three Act Tragedy", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=CvsCA2ZNTHEC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "Predictable, says Hercule Poirot, the great detective. But entirely unpredictable is that he can find absolutely no motive for murder.… The novel opens as a theatre programme, with this telling credit: &#39;Illumination by HERCULE POIROT.")
Book.create(title: "Spider's Web", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=zgWRQSBqgfYC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "A classic from the original queen of mystery: Agatha Christie.")
Book.create(title: "While the Light Lasts", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=9i-y3FBJ5jMC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "A classic from the queen of mystery: Agatha Christie.")
Book.create(title: "The Third-Floor Flat: A Hercule Poirot Short Story", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=eZqlAQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "A classic Agatha Christie short story, available individually for the first time as an ebook.")
Book.create(title: "Ingots of Gold", author: "Agatha Christie", img_url: "http://books.google.com/books/content?id=PHkTLiBPVlsC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", description: "A classic Agatha Christie short story, featuring Miss Marple, from the collection Miss Marple: The Complete Short Stories.")
Shelf.create(name: "Currently Reading", user_id: 7)
Shelf.create(name: "Read", user_id: 7)
Shelving.create(book_id: 1, shelf_id: 1)
Shelving.create(book_id: 3, shelf_id: 1)
