Book.destroy_all
##Manual Book Seeds##
Book.create(title: "And Then There Were None", author: "Agatha Christie", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523300890/01.jpg", description: "First, there were ten—a curious assortment of strangers summoned as weekend guests to a private island off the coast of Devon. Their host, an eccentric millionaire unknown to all of them, is nowhere to be found. All that the guests have in common is a wicked past they're unwilling to reveal—and a secret that will seal their fate. For each has been marked for murder. One by one they fall prey. Before the weekend is out, there will be none. And only the dead are above suspicion.")
Book.create(title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523386598/05.jpg", description: "A groundbreaking work of science fiction, The Left Hand of Darkness tells the story of a lone human emissary to Winter, an alien world whose inhabitants can choose -and change - their gender. His goal is to facilitate Winter's inclusion in a growing intergalactic civilization. But to do so he must bridge the gulf between his own views and those of the completely dissimilar culture that he encounters.

Embracing the aspects of psychology, society, and human emotion on an alien world, The Left Hand of Darkness stands as a landmark achievement in the annals of intellectual science fiction.")
Book.create(title: "The Casual Vacancy", author: "J.K. Rowling", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523386284/03.jpg", description: "When Barry Fairbrother dies in his early forties, the town of Pagford is left in shock.

Pagford is, seemingly, an English idyll, with a cobbled market square and an ancient abbey, but what lies behind the pretty façade is a town at war.

Rich at war with poor, teenagers at war with their parents, wives at war with their husbands, teachers at war with their pupils ... Pagford is not what it first seems.

And the empty seat left by Barry on the parish council soon becomes the catalyst for the biggest war the town has yet seen. Who will triumph in an election fraught with passion, duplicity and unexpected revelations?")
Book.create(title: "Crime and Punishment", author: "Fyodor Mikhaylovich Dostoyevsky", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523386227/02.jpg", description: "Raskolnikov, an impoverished student living in the St. Petersburg of the tsars, is determined to overreach his humanity and assert his untrammeled individual will. When he commits an act of murder and theft, he sets into motion a story that, for its excruciating suspense, its atmospheric vividness, and its depth of characterization and vision is almost unequaled in the literatures of the world. The best known of Dostoevsky’s masterpieces, Crime and Punishment can bear any amount of rereading without losing a drop of its power over our imaginations.

Dostoevsky’s drama of sin, guilt, and redemption transforms the sordid story of an old woman’s murder into the nineteenth century’s profoundest and most compelling philosophical novel.

Award-winning translators Richard Pevear and Larissa Volokhonsky render this elusive and wildly innovative novel with an energy, suppleness, and range of voice that do full justice to the genius of its creator.")
Book.create(title: "Notes from the Underground", author: "Fyodor Mikhaylovich Dostoyevsky", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523386434/04.jpg", description: "Dostoevsky’s most revolutionary novel, Notes from Underground marks the dividing line between nineteenth- and twentieth-century fiction, and between the visions of self each century embodied. One of the most remarkable characters in literature, the unnamed narrator is a former official who has defiantly withdrawn into an underground existence. In full retreat from society, he scrawls a passionate, obsessive, self-contradictory narrative that serves as a devastating attack on social utopianism and an assertion of man’s essentially irrational nature.

Richard Pevear and Larissa Volokhonsky, whose Dostoevsky translations have become the standard, give us a brilliantly faithful edition of this classic novel, conveying all the tragedy and tormented comedy of the original.")
Book.create(title: "The Girl with the Dragon Tattoo (Millennium #1)
", author: "Stieg Larsson", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523634668/2429135.jpg", description: "It’s about the disappearance forty years ago of Harriet Vanger, a young scion of one of the wealthiest families in Sweden . . . and about her octogenarian uncle, determined to know the truth about what he believes was her murder.

It’s about Mikael Blomkvist, a crusading journalist recently at the wrong end of a libel case, hired to get to the bottom of Harriet’s disappearance . . . and about Lisbeth Salander, a twenty-four-year-old pierced and tattooed genius hacker possessed of the hard-earned wisdom of someone twice her age—and a terrifying capacity for ruthlessness to go with it—who assists Blomkvist with the investigation. This unlikely team discovers a vein of nearly unfathomable iniquity running through the Vanger family, astonishing corruption in the highest echelons of Swedish industrialism—and an unexpected connection between themselves.

It’s a contagiously exciting, stunningly intelligent novel about society at its most hidden, and about the intimate lives of a brilliantly realized cast of characters, all of them forced to face the darker aspects of their world and of their own lives.")
Book.create(title: "The Little Prince", author: " Antoine de Saint-Exupéry", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523634747/157993.jpg", description: "Moral allegory and spiritual autobiography, The Little Prince is the most translated book in the French language. With a timeless charm it tells the story of a little boy who leaves the safety of his own tiny planet to travel the universe, learning the vagaries of adult behaviour through a series of extraordinary encounters. His personal odyssey culminates in a voyage to Earth and further adventures.")
Book.create(title: "The Invisible Man", author: "Ralph Ellison", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523634887/16981.jpg", description: "First published in 1952 and immediately hailed as a masterpiece, Invisible Man is one of those rare novels that have changed the shape of American literature. For not only does Ralph Ellison's nightmare journey across the racial divide tell unparalleled truths about the nature of bigotry and its effects on the minds of both victims and perpetrators, it gives us an entirely new model of what a novel can be.

As he journeys from the Deep South to the streets and basements of Harlem, from a horrifying battle royale where black men are reduced to fighting animals, to a Communist rally where they are elevated to the status of trophies, Ralph Ellison's nameless protagonist ushers readers into a parallel universe that throws our own into harsh and even hilarious relief. Suspenseful and sardonic, narrated in a voice that takes in the symphonic range of the American language, black and white, Invisible Man is one of the most audacious and dazzling novels of our century.")
Book.create(title: "Slaughterhouse-Five", author: "Kurt Vonnegut", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523635077/4981.jpg", description: "Selected by the Modern Library as one of the 100 best novels of all time, Slaughterhouse-Five, an American classic, is one of the world's great antiwar books. Centering on the infamous firebombing of Dresden, Billy Pilgrim's odyssey through time reflects the mythic journey of our own fractured lives as we search for meaning in what we fear most.")
Book.create(title: "Siddhartha", author: "Herman Hesse", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523635178/52036.jpg", description: "Herman Hesse's classic novel has delighted, inspired, and influenced generations of readers, writers, and thinkers. In this story of a wealthy Indian Brahmin who casts off a life of privilege to seek spiritual fulfillment. Hesse synthesizes disparate philosophies--Eastern religions, Jungian archetypes, Western individualism--into a unique vision of life as expressed through one man's search for meaning.")
Book.create(title: "Middlesex", author: "Jeffrey Eugenides", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523635285/2187.jpg", description: "Middlesex tells the breathtaking story of Calliope Stephanides, and three generations of the Greek-American Stephanides family, who travel from a tiny village overlooking Mount Olympus in Asia Minor to Prohibition-era Detroit, witnessing its glory days as the Motor City and the race riots of 1967 before moving out to the tree-lined streets of suburban Grosse Pointe, Michigan. To understand why Calliope is not like other girls, she has to uncover a guilty family secret, and the astonishing genetic history that turns Callie into Cal, one of the most audacious and wondrous narrators in contemporary fiction. Lyrical and thrilling, Middlesex is an exhilarating reinvention of the American epic. ")
Book.create(title: "Catcher in the Rye", author: "J.D. Salinger", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523635368/5107.jpg", description: "The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days. The boy himself is at once too simple and too complex for us to make any final comment about him or his story. Perhaps the safest thing we can say about Holden is that he was born in the world not just strongly attracted to beauty but, almost, hopelessly impaled on it. There are many voices in this novel: children's voices, adult voices, underground voices-but Holden's voice is the most eloquent of all. Transcending his own vernacular, yet remaining marvelously faithful to it, he issues a perfectly articulated cry of mixed pain and pleasure. However, like most lovers and clowns and poets of the higher orders, he keeps most of the pain to, and for, himself. The pleasure he gives away, or sets aside, with all his heart. It is there for the reader who can handle it to keep. ")
Book.create(title: "Animal Farm", author: "George Orwell", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523635496/7613.jpg", description: "As ferociously fresh as it was more than a half century ago, this remarkable allegory of a downtrodden society of overworked, mistreated animals, and their quest to create a paradise of progress, justice, and equality is one of the most scathing satires ever published. As we witness the rise and bloody fall of the revolutionary animals, we begin to recognize the seeds of totalitarianism in the most idealistic organization; and in our most charismatic leaders, the souls of our cruelest oppressors.")
Book.create(title: "Life of Pi", author: "Yann Matel", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523635586/4214.jpg", description: "Life of Pi is a fantasy adventure novel by Yann Martel published in 2001. The protagonist, Piscine Molitor \"Pi\" Patel, a Tamil boy from Pondicherry, explores issues of spirituality and practicality from an early age. He survives 227 days after a shipwreck while stranded on a boat in the Pacific Ocean with a Bengal tiger named Richard Parker.")
Book.create(title: "Moby Dick", author: "Herman Melville", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523635701/153747.jpg", description: "\"It is the horrible texture of a fabric that should be woven of ships' cables and hawsers. A Polar wind blows through it, and birds of prey hover over it.\"

So Melville wrote of his masterpiece, one of the greatest works of imagination in literary history. In part, Moby-Dick is the story of an eerily compelling madman pursuing an unholy war against a creature as vast and dangerous and unknowable as the sea itself. But more than just a novel of adventure, more than an encyclopaedia of whaling lore and legend, the book can be seen as part of its author's lifelong meditation on America. Written with wonderfully redemptive humour, Moby-Dick is also a profound inquiry into character, faith, and the nature of perception.")
Book.create(title: "To Kill A Mockingbird", author: "Harper Lee", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523635858/2657.jpg", description: "Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.")
Book.create(title: "The Trial", author: "Franz Kafka", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523636253/17690.jpg", description: "Written in 1914 but not published until 1925, a year after Kafka’s death, The Trial is the terrifying tale of Josef K., a respectable bank officer who is suddenly and inexplicably arrested and must defend himself against a charge about which he can get no information. Whether read as an existential tale, a parable, or a prophecy of the excesses of modern bureaucracy wedded to the madness of totalitarianism, The Trial has resonated with chilling truth for generations of readers.")
Book.create(title: "Foundation (Foundation #1 )", author: "Isaac Asimov", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523636363/29579.jpg", description: "For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future -- to a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save mankind, Seldon gathers the best minds in the Empire -- both scientists and scholars -- and brings them to a bleak planet at the edge of the Galaxy to serve as a beacon of hope for a future generations. He calls his sanctuary the Foundation.

But soon the fledgling Foundation finds itself at the mercy of corrupt warlords rising in the wake of the receding Empire. Mankind's last best hope is faced with an agonizing choice: submit to the barbarians and be overrun -- or fight them and be destroyed.")
Book.create(title: "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy #1)", author: "Douglas Adams", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523636562/11.jpg", description: "Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.

Together this dynamic pair begin a journey through space aided by quotes from The Hitchhiker's Guide (\"A towel is about the most massively useful thing an interstellar hitchhiker can have\") and a galaxy-full of fellow travelers: Zaphod Beeblebrox—the two-headed, three-armed ex-hippie and totally out-to-lunch president of the galaxy; Trillian, Zaphod's girlfriend (formally Tricia McMillan), whom Arthur tried to pick up at a cocktail party once upon a time zone; Marvin, a paranoid, brilliant, and chronically depressed robot; Veet Voojagig, a former graduate student who is obsessed with the disappearance of all the ballpoint pens he bought over the years.")
Book.create(title: "The Alchemist", author: "Paulo Coelho", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523636714/865.jpg", description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams")
Book.create(title: "Colorless Tsukuru Tazaki and His Years of Pilgrimage", author: "Haruki Murakami", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523637094/19288239.jpg", description: "An instant #1 New York Times Bestseller, Colorless Tsukuru Tazaki and His Years of Pilgrimage is the remarkable story of a young man haunted by a great loss; of dreams and nightmares that have unintended consequences for the world around us; and of a journey into the past that is necessary to mend the present. Here Haruki Murakami—one of the most revered voices in literature today—gives us a story of love, friend­ship, and heartbreak for the ages.")
Book.create(title: "The Absolutely True Diary of a Part-Time Indian", author: "Sherman Alexie", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523637037/693208.jpg", description: "Heartbreaking, funny, and beautifully written, The Absolutely True Diary of a Part-Time Indian, which is based on the author's own experiences, coupled with poignant drawings by Ellen Forney that reflect the character's art, chronicles the contemporary adolescence of one Native American boy as he attempts to break away from the life he was destined to live.

With a forward by Markus Zusak, interviews with Sherman Alexie and Ellen Forney, and four-color interior art throughout, this edition is perfect for fans and collectors alike. ")
Book.create(title: "Wind-Up Bird Chronicle", author: "Haruki Murakami", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523637289/11275.jpg", description: "In a Tokyo suburb a young man named Toru Okada searches for his wife's missing cat. Soon he finds himself looking for his wife as well in a netherworld that lies beneath the placid surface of Tokyo. As these searches intersect, Okada encounters a bizarre group of allies and antagonists: a psychic prostitute; a malevolent yet mediagenic politician; a cheerfully morbid sixteen-year-old-girl; and an aging war veteran who has been permanently changed by the hideous things he witnessed during Japan's forgotten campaign in Manchuria.

Gripping, prophetic, suffused with comedy and menace, The Wind-Up Bird Chronicle is a tour de force equal in scope to the masterpieces of Mishima and Pynchon.")
Book.create(title: "Snow Flower and the Secret Fan", author: "Lisa See", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523637439/1103.jpg", description: "In nineteenth-century China, in a remote Hunan county, a girl named Lily, at the tender age of seven, is paired with a laotong, “old same,” in an emotional match that will last a lifetime. The laotong, Snow Flower, introduces herself by sending Lily a silk fan on which she’s painted a poem in nu shu, a unique language that Chinese women created in order to communicate in secret, away from the influence of men.

As the years pass, Lily and Snow Flower send messages on fans, compose stories on handkerchiefs, reaching out of isolation to share their hopes, dreams, and accomplishments. Together, they endure the agony of foot-binding, and reflect upon their arranged marriages, shared loneliness, and the joys and tragedies of motherhood. The two find solace, developing a bond that keeps their spirits alive. But when a misunderstanding arises, their deep friendship suddenly threatens to tear apart.")
Book.create(title: "Gravity's Rainbow", author: "Thomas Pynchon", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523637576/415.jpg", description: "Winner of the 1973 National Book Award, Gravity's Rainbow is a postmodern epic, a work as exhaustively significant to the second half of the 20th century as Joyce's Ulysses was to the first. Its sprawling, encyclopedic narrative and penetrating analysis of the impact of technology on society make it an intellectual tour de force.")
Book.create(title: "Grapes of Wrath", author: "John Steinbeck", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523637775/18114322.jpg", description: "First published in 1939, Steinbeck’s Pulitzer Prize winning epic of the Great Depression chronicles the Dust Bowl migration of the 1930s and tells the story of one Oklahoma farm family, the Joads, driven from their homestead and forced to travel west to the promised land of California. Out of their trials and their repeated collisions against the hard realities of an America divided into haves and have-nots evolves a drama that is intensely human yet majestic in its scale and moral vision, elemental yet plainspoken, tragic but ultimately stirring in its human dignity.

A portrait of the conflict between the powerful and the powerless, of one man’s fierce reaction to injustice, and of one woman’s stoical strength, the novel captures the horrors of the Great Depression and probes the very nature of equality and justice in America.
")
Book.create(title: "Hunter x Hunter", author: "Togashi, Yoshihiro", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523637982/192445.jpg", description: "Hunters are a special breed, dedicated to tracking down treasures, magical beasts, and even other men. But such pursuits require a license, and less than one in a hundred thousand can pass the grueling qualification exam. Those who do pass gain access to restricted areas, amazing stores of information, and the right to call themselves Hunters. ")
Book.create(title: "The Metamorphosis", author: "Franz Kafka", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523638232/485894.jpg", description: "\"As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into a gigantic insect. He was laying on his hard, as it were armor-plated, back and when he lifted his head a little he could see his domelike brown belly divided into stiff arched segments on top of which the bed quilt could hardly keep in position and was about to slide off completely. His numerous legs, which were pitifully thin compared to the rest of his bulk, waved helplessly before his eyes.\"

With this startling, bizarre, yet surprisingly funny first opening, Kafka begins his masterpiece, The Metamorphosis. It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing -- though absurdly comic -- meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ")
Book.create(title: "Alice's Adventures in Wonderland (Alice's Adventures in Wonderland #1)", author: "Lewis Carroll", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523638359/6324090.jpg", description: "After a tumble down the rabbit hole, Alice finds herself far away from home in the absurd world of Wonderland. As mind-bending as it is delightful, Lewis Carroll’s 1865 novel is pure magic for young and old alike.")
Book.create(title: "Love in the Time of Cholera", author: " Gabriel García Márquez", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523638532/9712.jpg", description: "In their youth, Florentino Ariza and Fermina Daza fall passionately in love. When Fermina eventually chooses to marry a wealthy, well-born doctor, Florentino is devastated, but he is a romantic. As he rises in his business career he whiles away the years in 622 affairs--yet he reserves his heart for Fermina. Her husband dies at last, and Florentino purposefully attends the funeral. Fifty years, nine months, and four days after he first declared his love for Fermina, he will do so again.")
Book.create(title: "The Devotion of Suspect X", author: "Keigo Higashino", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523638782/8686068.jpg", description: "Yasuko Hanaoka is a divorced, single mother who thought she had finally escaped her abusive ex-husband Togashi. When he shows up one day to extort money from her, threatening both her and her teenaged daughter Misato, the situation quickly escalates into violence and Togashi ends up dead on her apartment floor. Overhearing the commotion, Yasuko’s next door neighbor, middle-aged high school mathematics teacher Ishigami, offers his help, disposing not only of the body but plotting the cover-up step-by-step.

When the body turns up and is identified, Detective Kusanagi draws the case and Yasuko comes under suspicion. Kusanagi is unable to find any obvious holes in Yasuko’s manufactured alibi and yet is still sure that there’s something wrong. Kusanagi brings in Dr. Manabu Yukawa, a physicist and college friend who frequently consults with the police. Yukawa, known to the police by the nickname Professor Galileo, went to college with Ishigami. After meeting up with him again, Yukawa is convinced that Ishigami had something to do with the murder. What ensues is a high level battle of wits, as Ishigami tries to protect Yasuko by outmaneuvering and outthinking Yukawa, who faces his most clever and determined opponent yet.")
Book.create(title: "The Ones Who Walk Away from Omelas", author: "Ursula K. Le Guin", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523638933/92625.jpg", description: "Some inhabitants of a peaceful kingdom cannot tolerate the act of cruelty that underlies its happiness.
The story \"Omelas\" was first published in New Dimensions 3, a hard-cover science fiction anthology edited by Robert Silverberg, in October 1973, and the following year it won Le Guin the prestigious Hugo Award for best short story.
It was subsequently printed in her short story collection The Wind's Twelve Quarters in 1975.")
Book.create(title: "Wonder", author: "R.J. Palacio", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523638658/11387515.jpg", description: "I won’t describe what I look like. Whatever you’re thinking, it’s probably worse.

August Pullman was born with a facial difference that, up until now, has prevented him from going to a mainstream school. Starting 5th grade at Beecher Prep, he wants nothing more than to be treated as an ordinary kid—but his new classmates can’t get past Auggie’s extraordinary face. WONDER, now a #1 New York Times bestseller and included on the Texas Bluebonnet Award master list, begins from Auggie’s point of view, but soon switches to include his classmates, his sister, her boyfriend, and others. These perspectives converge in a portrait of one community’s struggle with empathy, compassion, and acceptance")
Book.create(title: "The Hobbit", author: "J.R.R. Tolkein", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523639086/5907.jpg", description: "Written for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent. The text in this 372-page paperback edition is based on that first published in Great Britain by Collins Modern Classics (1998), and includes a note on the text by Douglas A. Anderson (2001). Unforgettable!")
Book.create(title: "The Stranger", author: "Albert Camus", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523639204/49552.jpg", description: "Through the story of an ordinary man unwittingly drawn into a senseless murder on an Algerian beach, Camus explored what he termed \"the nakedness of man faced with the absurd.\" First published in English in 1946; now in a new translation by Matthew Ward.")
Book.create(title: "An Anthropologist on Mars: Seven Paradoxical Tales", author: "Oliver Sacks", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523639279/64666.jpg", description: "Paradoxical portraits of seven neurological patients, including a surgeon consumed by the compulsive tics of Tourette's syndrome unless he is operating; an artist who loses all sense of color in a car accident, but finds new creative power in black & white; & others.")
Book.create(title: "Windup Girl", author: " Paolo Bacigalupi", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523639833/6597651.jpg", description: "Anderson Lake is a company man, AgriGen's Calorie Man in Thailand. Under cover as a factory manager, Anderson combs Bangkok's street markets in search of foodstuffs thought to be extinct, hoping to reap the bounty of history's lost calories. There, he encounters Emiko...

Emiko is the Windup Girl, a strange and beautiful creature. One of the New People, Emiko is not human; instead, she is an engineered being, creche-grown and programmed to satisfy the decadent whims of a Kyoto businessman, but now abandoned to the streets of Bangkok. Regarded as soulless beings by some, devils by others, New People are slaves, soldiers, and toys of the rich in a chilling near future in which calorie companies rule the world, the oil age has passed, and the side effects of bio-engineered plagues run rampant across the globe.

What Happens when calories become currency? What happens when bio-terrorism becomes a tool for corporate profits, when said bio-terrorism's genetic drift forces mankind to the cusp of post-human evolution? Award-winning author Paolo Bacigalupi delivers one of the most highly acclaimed science fiction novels of the twenty-first century.")
Book.create(title: "Red Rising (Red Rising Saga #1)", author: "Pierce Brown", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523639921/15839976.jpg", description: "Darrow is a Red, a member of the lowest caste in the color-coded society of the future. Like his fellow Reds, he works all day, believing that he and his people are making the surface of Mars livable for future generations.

Yet he spends his life willingly, knowing that his blood and sweat will one day result in a better world for his children.

But Darrow and his kind have been betrayed. Soon he discovers that humanity already reached the surface generations ago. Vast cities and sprawling parks spread across the planet. Darrow—and Reds like him—are nothing more than slaves to a decadent ruling class.

Inspired by a longing for justice, and driven by the memory of lost love, Darrow sacrifices everything to infiltrate the legendary Institute, a proving ground for the dominant Gold caste, where the next generation of humanity's overlords struggle for power. He will be forced to compete for his life and the very future of civilization against the best and most brutal of Society's ruling class. There, he will stop at nothing to bring down his enemies... even if it means he has to become one of them to do so.")
Book.create(title: "THe Abyss", author: "Orson Scott Card", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523639980/40289.jpg", description: "From the author of \"Speaker's for the Dead\", and \"Seventh Son\", this science fiction thriller is set in the Caribbean where a US submarine is mysteriously attacked. Foul play by the Soviets is suspected, and the world draws close to nuclear war. But the answer has nothing to do with human deeds.")
Book.create(title: "Their Eyes Were Watching God", author: "Zora Neale Hurston", img_url: "http://res.cloudinary.com/dqj3kgpoj/image/upload/v1523640108/37415.jpg", description: "Fair and long-legged, independent and articulate, Janie Crawford sets out to be her own person -- no mean feat for a black woman in the '30s. Janie's quest for identity takes her through three marriages and into a journey back to her roots.
")

#User Seeds##
  25.times do
    name = Faker::Name.first_name
    password = Faker::Internet.password
    user = User.create(username: name, password: password);
  end


##Reviews Seeds##
  i = 1
  while i < 41
    5.times do
      body = Faker::HarryPotter.quote
      rating = Faker::Number.between(1, 5)
      user_id = Faker::Number.between(1, 25)
      book_id = i
      review = Review.create(body: body, rating: rating, user_id: user_id, book_id: book_id)
    end
    i += 1
  end
